dbt_hol:
  target: QA
  outputs:
    QA:
      type: snowflake
      ######## Please replace with your Snowflake account name
      account: bm12759.ap-south-1.aws
      
      user: AMBYINT_TEST
      ######## Please replace with your Snowflake dbt user password
      password: Ambyint1234
      
      role: ACCOUNTADMIN
      database: DBT
      warehouse: COMPUTE_WH
      schema: public
      threads: 200
      client_session_keep_alive: False
      query_tag: github_action_query
    prod:
      type: snowflake
      ######## Please replace with your Snowflake account name
      account: zr43462.eu-central-1
      
      user: dbt_user
      ######## Please replace with your Snowflake dbt user password
      password: dbtPWD@11
      
      role: dbt_prod_role
      database: dbt_hol_prod
      warehouse: dbt_prod_wh
      schema: public
      threads: 200
      client_session_keep_alive: False
      query_tag: github_action_query
    view:
      type: snowflake
      ######## Please replace with your Snowflake account name
      account: zr43462.eu-central-1
      
      user: dbt_user
      ######## Please replace with your Snowflake dbt user password
      password: dbtPWD@11
      
      role: dbt_dev_role
      database: dbt_hol_dev
      warehouse: dbt_dev_wh
      schema: test
      threads: 200
      client_session_keep_alive: False
      query_tag: github_action_query
default:
     outputs:
       dev:
       type: snowflake
       threads: 1
       account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
       user: "{{ env_var('DBT_SNOWFLAKE_USERNAME') }}"
       role: "{{ env_var('DBT_SNOWFLAKE_ROLE') }}"
       password: "{{ env_var('DBT_SNOWFLAKE_PW') }}"
       database: "{{ env_var('DBT_SNOWFLAKE_DATABASE') }}"
       warehouse: "{{ env_var('DBT_SNOWFLAKE_WAREHOUSE') }}"
       schema: "{{ env_var('DBT_SNOWFLAKE_SCHEMA') }}"
       client_session_keep_alive: False
       query_tag: github_action_query
